### ISSUE TITLE
Error when logging in

### ISSUE THREAD

**Issue by axelolsson** [chas-academy/05-dynamisk-webbplats-php-martinfjant#3]
After attempting to log in the form post goes to the following URL:

http://blog.martinfj.chas.academy/login

Which gives me an error. In fact, all other routes you have throw an error. Which leads me to believe:

1. Your .htaccess-file on Binero is not configured correctly. I can help you with that.
2. What's deployed on Binero doesn't actually reflect what you have in your codebase.

**Comment by martinfjant** [comment]
fixat
